name       : autopep8
version    : 1.6.0
release    : 7
source     :
    - https://github.com/hhatto/autopep8/archive/refs/tags/v1.6.0.tar.gz : 2c41c9f89d9fbf28a23b18e6f95add870e11f7d19010d3e96003fa396122a67d
homepage   : https://github.com/hhatto/autopep8
license    : MIT
component  : programming.python
summary    : Python auto formatting tool
description: |
    A tool that automatically formats Python code to conform to the PEP 8 style guide.
builddeps  :
    - pkgconfig(python3)
    - pycodestyle
    - python-toml
    - python-pytest
rundeps    :
    - pycodestyle
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v -k 'not io_error' # two io_error tests fail only in solbuild
