name       : autopep8
version    : 1.4.4
release    : 4
source     :
    - https://github.com/hhatto/autopep8/archive/v1.4.4.tar.gz : 7ec12f04caaf357ec4d19a832c2f65434cc1cc2d12db6eb7d6d5131565f45754
license    : MIT
component  : programming.python
summary    : Python auto formatting tool.
description: |
    A tool that automatically formats Python code to conform to the PEP 8 style guide.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
    - pycodestyle
rundeps    :
    - pycodestyle
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
check      : |-
    %python_test test/test_autopep8.py
    %python3_test test/test_autopep8.py
