name       : autopep8
version    : 1.5.4
release    : 5
source     :
    - https://github.com/hhatto/autopep8/archive/v1.5.4.tar.gz : e941d1fa1bfe50bd919d6b738f98b353c012e700ee8f1f276ff6e5d7a61d34db
license    : MIT
component  : programming.python
summary    : Python auto formatting tool.
description: |
    A tool that automatically formats Python code to conform to the PEP 8 style guide.
builddeps  :
    - pkgconfig(python3)
    - pycodestyle
    - python-toml
rundeps    :
    - pycodestyle
    - python-toml
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test test/test_autopep8.py
